name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish installers (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true

      - name: Build and publish (Windows)
        if: runner.os == 'Windows'
        run: npx electron-builder --win nsis msi --publish always

      - name: Build and publish (Linux)
        if: runner.os == 'Linux'
        run: npx electron-builder --linux deb --publish always

      - name: Build and publish (macOS)
        if: runner.os == 'macOS'
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npx electron-builder --mac dmg zip pkg --publish always 